Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 1101, in _main
    main()
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 889, in main
    operation_func(esp, args)
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/cmds.py", line 640, in write_flash
    res = esp.flash_md5sum(address, uncsize)
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 131, in inner
    return func(*args, **kwargs)
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 1073, in flash_md5sum
    res = self.check_command(
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 439, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 426, in command
    self._port.timeout = saved_timeout
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/serial/serialutil.py", line 372, in timeout
    self._reconfigure_port()
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 524, in _reconfigure_port
    self._set_special_baudrate(custom_baud)
  File "/Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 225, in _set_special_baudrate
    fcntl.ioctl(self.fd, IOSSIOSPEED, buf, 1)
OSError: [Errno 6] Device not configured
CMake Error at run_serial_tool.cmake:66 (message):
  
  /Users/noahrobitshek/.espressif/python_env/idf5.2_py3.10_env/bin/python;;/Users/noahrobitshek/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



